id: IF85BB939
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T21:47:37+00:00'
last_modified: '2022-06-09T08:39:39.345714+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6091
  title: དེང་རབས་བོད་སྨན་ཆུ་ཁབ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    AA58:
      image_group_id: I1KG6283
      title: Volume 1 of deng rabs bod sman chu khab
      total_pages: 118
      order: 1
      base_file: AA58.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
